### ISSUE TITLE
Do you know why the Doppler dimension size is 64?

### ISSUE THREAD

**Issue by Gang-Chen-China** [Toytiny/RadarOcc#4]
Hi, thanks for your great work！When I read the paper of K-radar dataset，the 4D Radar outpu data is 64x256x107x37，do you know why the doppler dimension size is 64?
<img width="590" alt="捕获" src="https://github.com/user-attachments/assets/a68f931b-9717-4919-b565-7fdbfc745813" />

**Comment by Ericwen2001** [comment]
This is due to the Doppler measurement range and resolution configured in the K-Radar sensor. The measurable range is -1.92 to 1.92 m/s ￼, and any measurements outside this range will overflow. For instance, if the relative speeds are 3.0 m/s and 6.0 m/s, they would be measured within the range of -1.92 to 1.92 m/s as 3.0 - 3.84 = -0.84 m/s and 6.0 - 3.84*2 = -1.68 m/s, respectively.

**Comment by Gang-Chen-China** [comment]
thank you!
